### ISSUE TITLE
'get_path_prob' is not defined.

### ISSUE THREAD

**Issue by FangRJ** [dgl-prc/rnn2automata#1]
Run the file ***experiments/effectiveness/pfa_predict.py*** to get the fidelity and accuracy of the learned pfa.

I had a problem with this step, that is "name 'get_path_prob' is not defined", I cannot find this function in the project.

**Comment by dgl-prc** [comment]
Sorry, my fault. The previous code was the old version, and I have uploaded the latest. Pull the new code and the problem will be fixed.
